### PR TITLE
Updated JSONLootBags to 1.12.2

### PR DESCRIPTION
**Pull request by Mordenkainen**
This commit should update JSONLootBags to 1.12.2.

### CODE REVIEW

**Review by dries007 — APPROVED** [review]
Neat

**Comment by dries007** [comment]
I wish I had time to test this, but the code looks great.
Hopefully Jenkins agrees with me there :)

**Comment by dries007** [comment]
Ok, so this is one of the few mods we have that actually has a compile time dependency on D3Core, but our maven server is no longer with us. Would you mind adding a flat-file folder with the [D3Core jenkins](https://jenkins.dries007.net/job/D3Core/) build in it?
I would do it myself, but I'm right in exam week :(

**Comment by Mordenkainen** [comment]
Sure, I will make another PR with that change after work.

**Pull request merged**
